ProxyPass /apache/backup-server/ http://127.0.0.1:8000/
ProxyPassReverse /apache/backup-server/ http://127.0.0.1:8000/

<Location /apache/backup-server>
    AuthType Basic
    AuthName "NovaNAS Backup Server"
    AuthUserFile /var/novanas/backup.htpasswd
    Require valid-user
</Location>
